colorScheme = "123factory"
defaultAppearance = "dark"
autoSwitchAppearance = true
copyright = "© { year } 123 Factory GmbH"

enableSearch = true
enableCodeCopy = true

mainSections = ["companies"]

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false
hotlinkFeatureImage = false

fingerprintAlgorithm = "sha512"

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/companies/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = false
  disableHeroImageFilter = false

[article]
  showDate = false
  showAuthor = false
  showBreadcrumbs = true
  showDraftLabel = true
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = false
  showTableOfContents = true
  showTaxonomies = false
  showCategories = true
  showTags = false
  showWordCount = false

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = false
  showCards = false
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false
  constrainItemsWidth = false

[taxonomy]
  showHero = false
  showBreadcrumbs = true
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

[term]
  showHero = false
  showBreadcrumbs = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]
